environment:
  name: prod
  project: cdf-bootcamp-03-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  #modules:
  #  bootcamp:
  CDF_PROJECT: cdf-bootcamp-03-prod # ex. cdf-bootcamp-01-test
  IDP_CLIENT_ID: ${IDP_CLIENT_ID} # replaced by .env
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET} # replaced by .env
  IDP_TENANT_ID: 16e3985b-ebe8-4e24-9da4-933e21a9fc81 # replaced by .env
  # This is related to the cluster where the CDF project is hosted.
  CDF_URL: https://westeurope-1.cognitedata.com
  IDP_SCOPES: https://westeurope-1.cognitedata.com/.default
  IDP_TOKEN_URL: ${IDP_TOKEN_URL} # replaced by .env
  # Groups
  
  data_developer_source_id: 690e6fbf-af79-4d3d-9fdc-d299e09a6a36
  data_pipeline_oee_source_id: 8f1e1db6-61ee-4887-bdd8-391e772deef1
  readwrite_source_id: da10903b-7975-47e1-8f6a-544da78fd987
  readonly_source_id: 8015daf6-a7a0-4ca7-bcbc-1815bedb370a
  icapi_extractors_source_id: 9ac9e19c-8d14-4d9c-9312-a944054c8785
  
  # Client Ids
  data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID} # replaced by .env
  data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET} # replaced by .env

  icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID} # replaced by .env
  icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET} # replaced by .env
  # Variables shared by modules
  icapi_ds_external_id: ds_icapi
  #use_cases:
  #  oee:
  uc_oee_ds_external_id: ds_uc_oee
